apiVersion : apps/v1
kind: Deployment
metadata:
  name: "wookiebookscluster-6ef8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "wookiebookscluster-6ef8"
  template:
    metadata:
      labels:
        app: "wookiebookscluster-6ef8"
    spec:
      containers:
        - name: "wookiebookscluster-6ef8"
          image: "toddbellamyregistry.azurecr.io/wookiebookscluster"
          ports:
          - containerPort: 80