on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: toddbellamyregistry.azurecr.io
        username: ${{ secrets.acr_toddbellamyregistry_username }}
        password: ${{ secrets.acr_toddbellamyregistry_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/WookieBooks.WebApi" -f  "WookieBooks.WebApi/Dockerfile" -t toddbellamyregistry.azurecr.io/wookiebookscluster:${{ github.sha }} --label dockerfile-path=WookieBooks.WebApi/Dockerfile
        docker push toddbellamyregistry.azurecr.io/wookiebookscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_wookiebookscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep wookiebooksclusterbdcf | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace wookiebooksclusterbdcf`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: wookiebooksclusterbdcf
        container-registry-url: toddbellamyregistry.azurecr.io
        container-registry-username: ${{ secrets.acr_toddbellamyregistry_username }}
        container-registry-password: ${{ secrets.acr_toddbellamyregistry_password }}
        secret-name: wookiebookscdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: wookiebooksclusterbdcf
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          toddbellamyregistry.azurecr.io/wookiebookscluster:${{ github.sha }}
        imagepullsecrets: |
          wookiebookscdockerauth
